# Generated by Django 4.2.13 on 2024-07-03 21:16

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InheritedMetaSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "initial_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True, null=True, verbose_name="Initial Range"
                    ),
                ),
                (
                    "current_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True, null=True, verbose_name="Current Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the span was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["initial_range"], name="initial_range_idx_19c4d2ee"),
                    models.Index(fields=["current_range"], name="current_range_idx_19c4d2ee"),
                    models.Index(fields=["initial_range", "deleted_at"], name="init_rng_del_at_idx_19c4d2ee"),
                    models.Index(fields=["current_range", "deleted_at"], name="curr_rng_del_at_idx_19c4d2ee"),
                    models.Index(fields=["deleted_at"], name="span_deleted_at_idx_19c4d2ee"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "initial_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        blank=True, null=True, verbose_name="Initial Range"
                    ),
                ),
                (
                    "current_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        blank=True, null=True, verbose_name="Current Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the span was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["initial_range"], name="initial_range_idx_3c106754"),
                    models.Index(fields=["current_range"], name="current_range_idx_3c106754"),
                    models.Index(fields=["initial_range", "deleted_at"], name="init_rng_del_at_idx_3c106754"),
                    models.Index(fields=["current_range", "deleted_at"], name="curr_rng_del_at_idx_3c106754"),
                    models.Index(fields=["deleted_at"], name="span_deleted_at_idx_3c106754"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteIntegerSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "initial_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True, null=True, verbose_name="Initial Range"
                    ),
                ),
                (
                    "current_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True, null=True, verbose_name="Current Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the span was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["initial_range"], name="initial_range_idx_91100e0a"),
                    models.Index(fields=["current_range"], name="current_range_idx_91100e0a"),
                    models.Index(fields=["initial_range", "deleted_at"], name="init_rng_del_at_idx_91100e0a"),
                    models.Index(fields=["current_range", "deleted_at"], name="curr_rng_del_at_idx_91100e0a"),
                    models.Index(fields=["deleted_at"], name="span_deleted_at_idx_91100e0a"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteDecimalSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "initial_range",
                    django.contrib.postgres.fields.ranges.DecimalRangeField(
                        blank=True, null=True, verbose_name="Initial Range"
                    ),
                ),
                (
                    "current_range",
                    django.contrib.postgres.fields.ranges.DecimalRangeField(
                        blank=True, null=True, verbose_name="Current Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the span was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["initial_range"], name="initial_range_idx_e7a43f02"),
                    models.Index(fields=["current_range"], name="current_range_idx_e7a43f02"),
                    models.Index(fields=["initial_range", "deleted_at"], name="init_rng_del_at_idx_e7a43f02"),
                    models.Index(fields=["current_range", "deleted_at"], name="curr_rng_del_at_idx_e7a43f02"),
                    models.Index(fields=["deleted_at"], name="span_deleted_at_idx_e7a43f02"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteDateTimeSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "initial_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        blank=True, null=True, verbose_name="Initial Range"
                    ),
                ),
                (
                    "current_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        blank=True, null=True, verbose_name="Current Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the span was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["initial_range"], name="initial_range_idx_92ab7513"),
                    models.Index(fields=["current_range"], name="current_range_idx_92ab7513"),
                    models.Index(fields=["initial_range", "deleted_at"], name="init_rng_del_at_idx_92ab7513"),
                    models.Index(fields=["current_range", "deleted_at"], name="curr_rng_del_at_idx_92ab7513"),
                    models.Index(fields=["deleted_at"], name="span_deleted_at_idx_92ab7513"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteDateSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "initial_range",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        blank=True, null=True, verbose_name="Initial Range"
                    ),
                ),
                (
                    "current_range",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        blank=True, null=True, verbose_name="Current Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the span was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["initial_range"], name="initial_range_idx_9e08fbec"),
                    models.Index(fields=["current_range"], name="current_range_idx_9e08fbec"),
                    models.Index(fields=["initial_range", "deleted_at"], name="init_rng_del_at_idx_9e08fbec"),
                    models.Index(fields=["current_range", "deleted_at"], name="curr_rng_del_at_idx_9e08fbec"),
                    models.Index(fields=["deleted_at"], name="span_deleted_at_idx_9e08fbec"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteBigIntegerSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "initial_range",
                    django.contrib.postgres.fields.ranges.BigIntegerRangeField(
                        blank=True, null=True, verbose_name="Initial Range"
                    ),
                ),
                (
                    "current_range",
                    django.contrib.postgres.fields.ranges.BigIntegerRangeField(
                        blank=True, null=True, verbose_name="Current Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the span was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["initial_range"], name="initial_range_idx_f357a4c1"),
                    models.Index(fields=["current_range"], name="current_range_idx_f357a4c1"),
                    models.Index(fields=["initial_range", "deleted_at"], name="init_rng_del_at_idx_f357a4c1"),
                    models.Index(fields=["current_range", "deleted_at"], name="curr_rng_del_at_idx_f357a4c1"),
                    models.Index(fields=["deleted_at"], name="span_deleted_at_idx_f357a4c1"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InheritedMetaSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segment_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True, null=True, verbose_name="Segment Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the segment was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "previous_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_segment",
                        to="example.inheritedmetasegment",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="example.inheritedmetaspan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Abstract Segments",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["segment_range"], name="segment_range_idx_8d7f88ba"),
                    models.Index(fields=["deleted_at"], name="seg_del_at_idx_8d7f88ba"),
                    models.Index(fields=["segment_range", "deleted_at"], name="seg_rng_del_at_idx_8d7f88ba"),
                    models.Index(fields=["span", "deleted_at"], name="span_del_at_idx_8d7f88ba"),
                    models.Index(fields=["previous_segment", "deleted_at"], name="prev_seg_del_at_idx_8d7f88ba"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segment_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        blank=True, null=True, verbose_name="Segment Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the segment was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "previous_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_segment",
                        to="example.eventsegment",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segments",
                        to="example.eventspan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["segment_range"], name="segment_range_idx_76a82e65"),
                    models.Index(fields=["deleted_at"], name="seg_del_at_idx_76a82e65"),
                    models.Index(fields=["segment_range", "deleted_at"], name="seg_rng_del_at_idx_76a82e65"),
                    models.Index(fields=["span", "deleted_at"], name="span_del_at_idx_76a82e65"),
                    models.Index(fields=["previous_segment", "deleted_at"], name="prev_seg_del_at_idx_76a82e65"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteIntegerSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segment_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True, null=True, verbose_name="Segment Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the segment was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "previous_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_segment",
                        to="example.concreteintegersegment",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="example.concreteintegerspan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Abstract Segments",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["segment_range"], name="segment_range_idx_e780ca84"),
                    models.Index(fields=["deleted_at"], name="seg_del_at_idx_e780ca84"),
                    models.Index(fields=["segment_range", "deleted_at"], name="seg_rng_del_at_idx_e780ca84"),
                    models.Index(fields=["span", "deleted_at"], name="span_del_at_idx_e780ca84"),
                    models.Index(fields=["previous_segment", "deleted_at"], name="prev_seg_del_at_idx_e780ca84"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteDecimalSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segment_range",
                    django.contrib.postgres.fields.ranges.DecimalRangeField(
                        blank=True, null=True, verbose_name="Segment Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the segment was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "previous_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_segment",
                        to="example.concretedecimalsegment",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="example.concretedecimalspan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Abstract Segments",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["segment_range"], name="segment_range_idx_cc724143"),
                    models.Index(fields=["deleted_at"], name="seg_del_at_idx_cc724143"),
                    models.Index(fields=["segment_range", "deleted_at"], name="seg_rng_del_at_idx_cc724143"),
                    models.Index(fields=["span", "deleted_at"], name="span_del_at_idx_cc724143"),
                    models.Index(fields=["previous_segment", "deleted_at"], name="prev_seg_del_at_idx_cc724143"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteDateTimeSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segment_range",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        blank=True, null=True, verbose_name="Segment Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the segment was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "previous_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_segment",
                        to="example.concretedatetimesegment",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="example.concretedatetimespan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Abstract Segments",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["segment_range"], name="segment_range_idx_8bca601e"),
                    models.Index(fields=["deleted_at"], name="seg_del_at_idx_8bca601e"),
                    models.Index(fields=["segment_range", "deleted_at"], name="seg_rng_del_at_idx_8bca601e"),
                    models.Index(fields=["span", "deleted_at"], name="span_del_at_idx_8bca601e"),
                    models.Index(fields=["previous_segment", "deleted_at"], name="prev_seg_del_at_idx_8bca601e"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteDateSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segment_range",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        blank=True, null=True, verbose_name="Segment Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the segment was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "previous_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_segment",
                        to="example.concretedatesegment",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="example.concretedatespan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Abstract Segments",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["segment_range"], name="segment_range_idx_e7aa5e72"),
                    models.Index(fields=["deleted_at"], name="seg_del_at_idx_e7aa5e72"),
                    models.Index(fields=["segment_range", "deleted_at"], name="seg_rng_del_at_idx_e7aa5e72"),
                    models.Index(fields=["span", "deleted_at"], name="span_del_at_idx_e7aa5e72"),
                    models.Index(fields=["previous_segment", "deleted_at"], name="prev_seg_del_at_idx_e7aa5e72"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConcreteBigIntegerSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segment_range",
                    django.contrib.postgres.fields.ranges.BigIntegerRangeField(
                        blank=True, null=True, verbose_name="Segment Range"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the segment was deleted.",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "previous_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_segment",
                        to="example.concretebigintegersegment",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="example.concretebigintegerspan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Abstract Segments",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["segment_range"], name="segment_range_idx_ff095aea"),
                    models.Index(fields=["deleted_at"], name="seg_del_at_idx_ff095aea"),
                    models.Index(fields=["segment_range", "deleted_at"], name="seg_rng_del_at_idx_ff095aea"),
                    models.Index(fields=["span", "deleted_at"], name="span_del_at_idx_ff095aea"),
                    models.Index(fields=["previous_segment", "deleted_at"], name="prev_seg_del_at_idx_ff095aea"),
                ],
            },
        ),
    ]
