# Generated by Django 4.2.13 on 2024-05-25 18:01

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventSpan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the span was deleted.",
                        null=True,
                        verbose_name="Deleted at",
                    ),
                ),
                ("initial_range", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ("current_range", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["initial_range"], name="example_eve_initial_ea4530_idx"),
                    models.Index(fields=["current_range"], name="example_eve_current_caa1f9_idx"),
                    models.Index(fields=["deleted_at"], name="example_eve_deleted_fb1e91_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the segment was deleted.",
                        null=True,
                        verbose_name="Deleted at",
                    ),
                ),
                ("segment_range", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ("event_span", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="example.eventspan")),
                (
                    "previous_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_segment",
                        to="example.eventsegment",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["segment_range"], name="example_eve_segment_8531e0_idx"),
                    models.Index(fields=["deleted_at"], name="example_eve_deleted_b015b4_idx"),
                ],
            },
        ),
    ]
